# Generated by Django 3.1.5 on 2021-01-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_cat',
            field=models.CharField(default='parts', max_length=50),
        ),
        migrations.AddField(
            model_name='products',
            name='product_class',
            field=models.CharField(default='class', max_length=50),
        ),
        migrations.AddField(
            model_name='products',
            name='product_type',
            field=models.CharField(default='accessory', max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(default='product', max_length=150),
        ),
    ]
