# Generated by Django 3.1.5 on 2021-02-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='d_price',
            field=models.FloatField(blank=True, default=-1, null=True),
        ),
    ]
