# Generated by Django 3.1.5 on 2021-01-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210110_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
