# Generated by Django 3.1.5 on 2021-01-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orderitem_is_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pictures',
            new_name='image',
        ),
    ]
