# Generated by Django 3.1.5 on 2021-01-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210124_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='fullname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
