# Generated by Django 3.1.5 on 2021-01-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210110_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='membership',
            field=models.CharField(choices=[('m', 'member'), ('g', 'gold')], max_length=1, null=True),
        ),
    ]
