# Generated by Django 3.1.5 on 2021-01-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210125_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_type',
            field=models.CharField(choices=[('H', 'Hot deals'), ('F', 'Featured'), ('N', 'New Arrivals'), ('B', 'Blocked'), ('D', 'Database')], default='D', max_length=1),
        ),
    ]
