# Generated by Django 3.1.5 on 2021-01-29 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_display_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.wishlist'),
        ),
    ]
